config/routes.rb
Rails.application.routes.draw do
  resources :tasks

  put '/tasks/:id/mark_as_done' => 'tasks#mark_as_done', :as => "mark_as_done"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy, :mark_as_done]

  def index
     @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    redirect_to task_path(@task)
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  def mark_as_done
    @task.update(done: true)
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:name, :description, :done)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task, html: { :class => "form-group" } do |f| %>
  <div class="form-group">
  <%= f.label :name %>
  <%= f.text_field :name, :class => "form-control" %>
  <%= f.label :description%>
  <%= f.text_field :description, :class => "form-control" %>
  </div>
  <%= f.submit 'create', :class=>"btn btn-primary "%>
<% end %>

app/views/tasks/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="back">
        <p>edit a task</p>
        <%= link_to "back", tasks_path, :class=>"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', task: @task %>
    </div>
  </div>
</div>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="menu">
        <%= link_to "new", new_task_path, :class=>"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <% @tasks.each do |task| %>
        <div class="task">
          <div class="task-name">
            <p>
            <% if task.done == true %>
                <i class="fa fa-check-square-o" aria-hidden="true"></i>
            <% else %>
              <%=  link_to mark_as_done_path(task.id), method: :put do %>
                <i class="fa fa-square-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
            </p>
          </div>
          <div class="task-body">
            <p><strong><%= task.name %></strong></p>
            <p>
              <%= task.description %>
            </p>
          </div>
          <div class="task-status">
            <%= link_to task_path(task), method: :delete do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
            <%= link_to edit_task_path(task) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="back">
        <p>Add a task</p>
        <%= link_to "back", tasks_path, :class=>"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= render 'form', task: @task %>
    </div>
  </div>
</div>

app/views/tasks/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="menu">
        <%= link_to "back", tasks_path, :class=>"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <div class="task">
        <div class="task-name">
            <p>
            <% if @task.done == true %>
                <i class="fa fa-check-square-o" aria-hidden="true"></i>
            <% else %>
              <%=  link_to mark_as_done_path(@task.id), method: :put do %>
                <i class="fa fa-square-o" aria-hidden="true"></i>
              <% end %>
            <% end %>
            </p>
          </div>
        <div class="task-body">
          <p><strong><%= @task.name %></strong></p>
          <p>
            <%= @task.description %>
          </p>
        </div>
        <div class="task-status">
            <%= link_to task_path(@task), method: :delete do %>
              <i class="fa fa-trash" aria-hidden="true"></i>
            <% end %>
            <%= link_to edit_task_path(@task) do %>
              <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</div>